### ISSUE TITLE
Naming Join Tables

### ISSUE THREAD

**Issue by nayana487** [ga-wdi-lessons/rails-many-to-many#5]
In pairs, spend 10 minutes answering the following questions for the below pairs of models...

Should the relationship between these two models be represented using a many-to-many relationship?
What would be a descriptive name for their resulting join table?
What would be a useful additional column to include in the join table (e.g., order)?
Models

Authors and Books
Students and Courses
Users and Groups
Blog Posts and Categories
Reddit Posts and Votes

**Comment by Tchase44** [comment]
Authors and Books = "collaberative_works", add ISBN#
Students and Courses = "Complete_Enorllment", add number courses each student is taking, start and end dates,
Users and Groups = see below
Blog Posts and Categories = see above
Reddit Posts and Votes = Not many to many.

**Comment by scottpiercew** [comment]
**Authors and Books**
1. many to many 
2. authorsBooks
3. published date, genre 

**Students and Courses**
1. many to many
2. schools
3. dates

**Users and Groups**
1. many to many
2. hangouts
3. locations 

**Blog Posts and Categories**
1. many to many 
2. blogCategories
3. creation date

**Reddit Posts and Votes**
1. one to many

**Comment by daniellefricke** [comment]
Authors & Books - Many to Many - AuthorBook - Author ID, Book ID 
Students & Courses - Many to Many - 'Attendance' or 'Schedule' - Student ID, Course ID
Users & Groups - Many to Many - 'AccountActivity' - User ID, Group ID, Events
Blog Posts & Categories - One to Many 
Reddit Posts & Votes - One to Many

**Comment by AskForTheWolf** [comment]
Many  to many "authorsbooks" Date
Many to many "studentcourses"  Time
Many to many "usergroups"  Time
Many to many "postcategories"  Categories
One to many "postvotes"  Votes

**Comment by BaoPham92** [comment]
Authors and Books many to many [auuthors => books]
Students and Courses many to many [grades_students => different_type_courses]
Users and Groups many to many [levels_and_types_users => types_groups]
Blog Posts and Categories many to many [blog_types => catering_types_categories]
Reddit Posts and Votes many to many [different_posts => different_votes]

**Comment by RobLowe1992** [comment]
1. I see believe that 1, 5 are one to many and that 2,3,4 are many to many
2. print_media, schedules, membership, blogagories, redit_info
3. year, semester, N/A , create_date,  create_date
